### ISSUE TITLE
Support for WHMCS 8.7.x and PHP 8.1

### ISSUE THREAD

**Issue by virtualos** [bitcartcc/whmcs-plugin#1]
Hello,

I recently found bitcart:
`https://lowendtalk.com/discussion/175065/whmcs-bitcoin-module`
and it sounds like WOW, great.

So does it support WHMCS 8.7.x and PHP 8.1?
If not, please add these requirements to whmcs module.

Thank you in advance.

**Comment by MrNaif2018** [comment]
Hi! I believe it should, please check. We can update metadata afterwards

**Comment by virtualos** [comment]
> Hi! I believe it should, please check. We can update metadata afterwards

Well, I've tested and seems it works on WHMCS 8.7.3 and PHP 8.1 however I got "invoice not found" error that I assume because of using demo panel and my wrong settings. I may run my own vps and will test it exactly but you may update the metadata as I got no whmcs famous oops error ;)

**Comment by virtualos** [comment]
Confirmation with Self-Hosted:
Everything works well wth no error in WHMCS 8.7.3(six, twenty-one & some custom templates tested) and PHP 8.1 All Ok. Thanks to me :D

Btw, Awesome job @MrNaif2018 Appreciate for making and sharing Bitcart.

**Comment by MrNaif2018** [comment]
Thank you for confirming! Will update metadata

**Comment by MrNaif2018** [comment]
Done!
